### ISSUE TITLE
Document K8S setup required for K8S resolver

### ISSUE THREAD

**Issue by tsegismont** [eclipse-vertx/vertx-service-resolver#4]
The Kube resolver requires the  `endpoints` resource to be accessible to the service account configured for the pod.

Here is an example configuration for role and role binding of the `default` service account:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: observe-endpoints
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: observe-endpoints
  namespace: default
roleRef:
  kind: Role
  name: observe-endpoints
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
```
